---
title: "R Notebook"
output:
  html_document: 
    highlight: pygments
  html_notebook: default
---


I will use earth package to implement the MARS. The data is in the AppliedPredictiveModeling R package.
```{r}
library(earth)
library(AppliedPredictiveModeling)
library(caret)
data(solubility)
## The data objects begin with "sol":
ls(pattern = "^solT")
```

Let's first see the data.
```{r}
head(solTestXtrans)
```

```{r}
head(solTrainY)
```


Using the nominal forward pass and pruning step
```{r}
marsFit <- earth(solTrainXtrans, solTrainY)
marsFit
```

```{r}
summary(marsFit)
```

```{r}
# Define the candidate models to test
marsGrid <- expand.grid(.degree = 1:2, .nprune = 2:38)
# Fix the seed so that the results can be reproduced
set.seed(100)
marsTuned <- train(solTrainXtrans, solTrainY, 
                   method = "earth",
                   # Explicitly declare the candidate models to test
                   tuneGrid = marsGrid,
                   trControl = trainControl(method = "cv"))
```